SmartBazaarWeb/Models/Site/CommentsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartBazaar.Web.Models.Site
{
    public class CommentsListViewModel
    {
        public string UserTitle { get; set; }
        public short Rating { get; set; }
        public DateTime Created { get; set; }
        public string Description { get; set; }
    }

    public class CommentsPostViewModel
    {
        public int ProductId { get; set; }
        public short Rating { get; set; }
        public string Description { get; set; }
    }
}

SmartBazaarWeb/Areas/Admin/Controllers/CatalogManagerController.cs
using Newtonsoft.Json;
using SmartBazaar.Web.Areas.Admin.Models;
using SmartBazaar.Web.Business.Workers;
using SmartBazaar.Web.Helpers.Excel;
using SmartBazaar.Web.Helpers.Extensions;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartBazaar.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admins")]
    public class CatalogManagerController : Controller
    {
        private readonly CatalogWorker m_catalogWorker;
        public CatalogManagerController()
        {
            m_catalogWorker = new CatalogWorker();
        }

        private TaxWorker GetTaxWorkerInstance()
        {
            return new TaxWorker();
        }

        #region Products

        // GET: Admin/CatalogManager
        
        public ActionResult Index(int page = 1, short status = 1, string ProductCode = null, string Caption = null, int? Category = null, int? Brand = null, int StockMin = int.MinValue, int StockMax = int.MaxValue, string export = null)
        {
            if (export == "excel")
            {
                return ExportExcel(status, ProductCode, Caption, Category, Brand, StockMin, StockMax);
            }
            ProductCode = string.IsNullOrWhiteSpace(ProductCode) ? null : ProductCode;
            Caption = string.IsNullOrWhiteSpace(Caption) ? null : Caption;

            ViewBag.Caption = Caption;
            ViewBag.ProductCode = ProductCode;
            ViewBag.StockMin = StockMin == int.MinValue ? (int?)null : StockMin;
            ViewBag.StockMax = StockMax == int.MaxValue ? (int?)null : StockMax;

            this.StatusList(status);
            ViewBag.Category = m_catalogWorker.GetCategorySelectLists();
            
            var brandList = m_catalogWorker.GetManagerCatalogBrandList(1);
            var brandSelectLists = brandList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString()}).ToList();
            ViewBag.Brand = brandSelectLists;

            ViewBag.CurrentPage = page;

            int[] catTree = { };
            if (Category.HasValue)
            {
                catTree = m_catalogWorker.GetCategorySubsTree(Category.Value);
            }

            var records = m_catalogWorker.GetManagerCatalogProductList( p => 
                    p.Status == status
                    && (ProductCode == null || p.ProductCode == ProductCode)
                    && (Caption == null || p.Title.Contains(Caption))
                    && (!Category.HasValue || catTree.Contains(p.CategoryId))
                    && (!Brand.HasValue || p.BrandId == Brand.Value)
                    && (p.Stock > StockMin && p.Stock < StockMax)
                );
            ViewBag.TotalPage = records.Count;
            var model = records.OrderBy(o => o.Title).Skip((page - 1) * AppConfig.PAGE_SIZE).Take(AppConfig.PAGE_SIZE).ToList();
            return View(model);
        }

        //GET: Admin/CatalogManager/Create
        public ActionResult Create()
        {
            var brandList = m_catalogWorker.GetManagerCatalogBrandList(1);
            var brandSelectLists = brandList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString() }).ToList();
            brandSelectLists.Insert(0, new SelectListItem { Text = "-", Value = "" });
            ViewBag.BrandId = brandSelectLists;
            var taxList = GetTaxWorkerInstance().GetManagerProductTaxList(1);
            ViewBag.TaxGroup = taxList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString() }).ToList();
            ViewBag.CategoryTree = m_catalogWorker.GetCategoryTree();
            this.StatusList(1);
            var model = new CatalogProductEditViewModel { 
                Status = 1,
                IsShipable = true,
                IsBuyable = true
            };
            ViewBag.Relations = JsonConvert.SerializeObject(model.Relations);
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CatalogProductEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    m_catalogWorker.InsertManagerCatalogProduct(model);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Generic", ex.Message);
                }
            }
            var brandList = m_catalogWorker.GetManagerCatalogBrandList(1);
            var brandSelectLists = brandList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString(), Selected = item.Id == model.BrandId }).ToList();
            brandSelectLists.Insert(0, new SelectListItem { Text = "-", Value = "" });
            ViewBag.BrandId = brandSelectLists;
            var taxList = GetTaxWorkerInstance().GetManagerProductTaxList(1);
            ViewBag.TaxGroup = taxList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString(), Selected = item.Id == model.TaxGroup }).ToList();
            ViewBag.CategoryTree = m_catalogWorker.GetCategoryTree();
            this.StatusList(model.Status);
            ViewBag.PropList = Newtonsoft.Json.JsonConvert.SerializeObject(model.Properties);
            ViewBag.Relations = JsonConvert.SerializeObject(model.Relations);
            return View(model);
        }

        //GET: Admin/CatalogManager/Edit
        public ActionResult Edit(int id)
        {
            try
            {
                var model = m_catalogWorker.GetManagerCatalogProductEdit(id);
                var brandList = m_catalogWorker.GetManagerCatalogBrandList(1);
                var brandSelectLists = brandList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString(), Selected = item.Id == model.BrandId }).ToList();
                brandSelectLists.Insert(0, new SelectListItem { Value = "", Text = "-" });
                ViewBag.BrandId = brandSelectLists;
                var taxList = GetTaxWorkerInstance().GetManagerProductTaxList(1);
                ViewBag.TaxGroup = taxList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString(), Selected = item.Id == model.TaxGroup }).ToList();
                ViewBag.CategoryTree = m_catalogWorker.GetCategoryTree();
                ViewBag.PropList = Newtonsoft.Json.JsonConvert.SerializeObject(model.Properties);
                ViewBag.ImgList = Newtonsoft.Json.JsonConvert.SerializeObject(model.Images);
                ViewBag.Relations = JsonConvert.SerializeObject(AutoMapper.Mapper.Map<List<Models.CatalogProductsRelationsEditViewModel>, List<Models.CatalogProductsRelationsJSONModel>>(model.Relations));
                this.StatusList(model.Status);
                
                return View(model);
            }
            catch (Exception ex)
            {
                this.ShowError(ex);
                return null;
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CatalogProductEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    m_catalogWorker.UpdateManagerCatalogProductEdit(model);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("General", ex.Message);
                }
            }
            var brandList = m_catalogWorker.GetManagerCatalogBrandList(1);
            var brandSelectLists = brandList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString(), Selected = item.Id == model.BrandId }).ToList();
            brandSelectLists.Insert(0, new SelectListItem { Text = "-" });
            ViewBag.BrandId = brandSelectLists;
            var taxList = GetTaxWorkerInstance().GetManagerProductTaxList(1);
            ViewBag.TaxGroup = taxList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString(), Selected = item.Id == model.TaxGroup }).ToList();
            ViewBag.CategoryTree = m_catalogWorker.GetCategoryTree();
            ViewBag.PropList = Newtonsoft.Json.JsonConvert.SerializeObject(model.Properties);
            ViewBag.Relations = JsonConvert.SerializeObject(AutoMapper.Mapper.Map<List<Models.CatalogProductsRelationsEditViewModel>, List<Models.CatalogProductsRelationsJSONModel>>(model.Relations));
            this.StatusList(model.Status);
            return View(model);
        }

        //GET: Admin/CatalogManager/Delete
        public ActionResult Delete(int id)
        {
            try
            {
                m_catalogWorker.DeleteManagerCatalogProductEdit(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.ShowError(ex);
                return null;
            }
        }

        public ActionResult MultiProcess()
        {
            var categoryList = m_catalogWorker.GetCategorySelectLists();
            categoryList.Insert(0, new SelectListItem { Text = "Tümü", Value = "" });
            ViewBag.category = categoryList;
            var brandList = m_catalogWorker.GetManagerCatalogBrandList(1);
            var brandSelectLists = brandList.Select(item => new SelectListItem { Text = item.Title, Value = item.Id.ToString() }).ToList();
            brandSelectLists.Insert(0, new SelectListItem { Text = "Tümü", Value = "" });
            ViewBag.brand = brandSelectLists;

            return View();
        }

        [HttpPost]
        public ActionResult MultiProcess(FormCollection frm)
        {
            short? status = string.IsNullOrWhiteSpace(frm["status"]) ? (short?)null : short.Parse(frm["status"]);

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/Brands.cshtml
@model IEnumerable<SmartBazaar.Web.Areas.Admin.Models.CatalogBrandListViewModel>

@{
    ViewBag.Title = "Markalar";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/ListLayout.cshtml";
    ViewBag.CreateUrl = @Url.Action("CreateBrand");
}

@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        @Html.ActionLink("Markalar", "Brands")
    </li>
}
@section Filters {
    <div class="form-group col-sm-9">
        <label class="control-label col-md-3 col-sm-4">@Html.DisplayNameFor(model => model.Title)</label>
        <div class="col-md-9 col-sm-8">
            @Html.DropDownList("Status", null, new { @class = "form-control" })
        </div>
    </div>
}

<tr>
    <th>
        @Html.DisplayNameFor(model => model.Title)
    </th>
    <th style="width: 100px;">
        @Html.DisplayNameFor(model => model.Status)
    </th>
    <th style="width: 140px;">

    </th>
</tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "EditBrand", new { id = item.Id }, new { @class = "label label-primary" })
            @Html.ActionLink("Sil", "DeleteBrand", new { id = item.Id }, new { @class = "label label-danger", onclick = "return confirm('Bu kayit silinsin mi?')" })
        </td>
    </tr>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/Categories.cshtml
@model IEnumerable<SmartBazaar.Web.Areas.Admin.Models.CatalogCategoryListViewModel>

@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/ListLayout.cshtml";
    ViewBag.CreateUrl = @Url.Action("CreateCategory");
}

@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        @Html.ActionLink("Kategoriler", "Categories")
    </li>
}
@section Filters {
    <div class="form-group col-sm-9">
        <label class="control-label col-md-3 col-sm-4">@Html.DisplayNameFor(model => model.Status)</label>
        <div class="col-md-9 col-sm-8">
            @Html.DropDownList("Status", null, new { @class = "form-control" })
        </div>
    </div>
}

<tr>
    <th>
        @Html.DisplayNameFor(model => model.Parent)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Caption)
    </th>
    <th style="width: 100px;">
        @Html.DisplayNameFor(model => model.Status)
    </th>
    <th style="width: 120px;"></th>
</tr>

@foreach (var item in Model.OrderBy(o => o.RowNr))
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Parent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Caption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "EditCategory", new { id = item.Id }, new { @class = "label label-primary" })
            @Html.ActionLink("Sil", "DeleteCategory", new { id = item.Id }, new { @class = "label label-danger", onclick = "return confirm('Kayit silinsin mi?')" })
        </td>
    </tr>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/CommentDetail.cshtml
@model SmartBazaar.Web.Areas.Admin.Models.CatalogCommentsDetailViewModel

@{
    ViewBag.Title = "Yorum Detayı";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/EditorLayout.cshtml";
    ViewBag.Subtitle = "Marka Bilgileri";
}

@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        @Html.ActionLink("Yorumlar", "Comments")
    </li>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-sm-3 col-md-3 col-lg-2">@Html.DisplayNameFor(model => model.UserTitle)</label>
            <div class="col-sm-9 col-md-9 col-lg-2">
                <span class="form-control-static">@Model.UserTitle</span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-md-3 col-lg-2">@Html.DisplayNameFor(model => model.ProductTitle)</label>
            <div class="col-sm-9 col-md-9 col-lg-2">
                <span class="form-control-static"><a href="@Url.Action("Edit", new { id = Model.ProductId })">@Model.ProductTitle</a></span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-md-3 col-lg-2">@Html.DisplayNameFor(model => model.Created)</label>
            <div class="col-sm-9 col-md-9 col-lg-2">
                <span class="form-control-static">@Model.Created</span>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-md-3 col-lg-2">@Html.DisplayNameFor(model => model.Rating)</label>
            <div class="col-sm-9 col-md-9 col-lg-2">
                <span class="form-control-static">@Model.Rating</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <span class="form-control-static">@Model.Description</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-md-offset-3 col-lg-offset-2 col-sm-9 col-md-9 col-lg-10">
                @if (Model.Status == 0)
                {
                    <input type="submit" name="op" value="Onayla" class="btn btn-success" />
                }
                <input type="submit" name="op" value="Sil" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/Comments.cshtml
@model IEnumerable<SmartBazaar.Web.Areas.Admin.Models.CatalogCommentsListViewModel>

@{
    ViewBag.Title = "Yorumlar";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/ListLayout.cshtml";
}

@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        @Html.ActionLink("Markalar", "Brands")
    </li>
}
@section Filters {
    <div class="form-group col-sm-9">
        <label class="control-label col-md-3 col-sm-4">@Html.DisplayNameFor(model => model.Status)</label>
        <div class="col-md-9 col-sm-8">
            @Html.DropDownList("Status", null, new { @class = "form-control" })
        </div>
    </div>
}

<tr>
    <th>@Html.DisplayNameFor(model => model.UserTitle)</th>
    <th>@Html.DisplayNameFor(model => model.ProductTitle)</th>
    <th style="width: 200px;">@Html.DisplayNameFor(model => model.Created)</th>
    <th style="width: 80px;">@Html.DisplayNameFor(model => model.Rating)</th>
    <th style="width: 120px;">@Html.DisplayNameFor(model => model.Status)</th>
    <th style="width: 140px;"></th>
</tr>
@foreach (var item in Model)
{
    <tr>
        <td>@Html.DisplayFor(model => item.UserTitle)</td>
        <td>@Html.DisplayFor(model => item.ProductTitle)</td>
        <td>@Html.DisplayFor(model => item.Created)</td>
        <td>@Html.DisplayFor(model => item.Rating)</td>
        <td>@Html.DisplayFor(model => item.Status)</td>
        <td>
            @Html.ActionLink("Detay", "CommentDetail", new { id = item.Id }, new { @class = "label label-primary" })
        </td>
    </tr>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/CreateBrand.cshtml
@model SmartBazaar.Web.Areas.Admin.Models.CatalogBrandEditViewModel

@{
    ViewBag.Title = "Markalar";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/EditorLayout.cshtml";
    ViewBag.Subtitle = "Yeni Marka Bilgileri";
}
@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        @Html.ActionLink("Markalar", "Brands")
    </li>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.Partial("CustomTemplates/ValidationSummary", ViewData.ModelState)
        @Html.EditorFor(model => model.Caption)
        @Html.EditorFor(model => model.Status)
        @Html.EditorFor(model => model.ExternalRef1)
        @Html.EditorFor(model => model.ExternalRef2)
        @Html.EditorFor(model => model.ExternalRef3)

        @Html.Partial("EditorTemplates/Submit")
    </div>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/EditBrand.cshtml
@model SmartBazaar.Web.Areas.Admin.Models.CatalogBrandEditViewModel

@{
    ViewBag.Title = "Markalar";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/EditorLayout.cshtml";
    ViewBag.Subtitle = "Marka Bilgileri";
}
@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        @Html.ActionLink("Markalar", "Brands")
    </li>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <div class="form-horizontal">

        @Html.Partial("CustomTemplates/ValidationSummary", ViewData.ModelState)
        @Html.EditorFor(model => model.Caption)
        @Html.EditorFor(model => model.Status)
        @Html.EditorFor(model => model.ExternalRef1)
        @Html.EditorFor(model => model.ExternalRef2)
        @Html.EditorFor(model => model.ExternalRef3)

        @Html.Partial("EditorTemplates/Submit")
    </div>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/ImportExcel.cshtml
@{
    ViewBag.Title = "Excel Alma";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/EditorLayout.cshtml";
    ViewBag.Subtitle = "Excel İle Ürün Alma";
}

@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
    </li>
}

<div class="note note-warning">
    <h4 class="block">Dikkat! Hatalı ürünleriniz hakkında</h4>
    <p>
        Sisteme yüklenecek Excel dosyası için ürün listesinin Excele aktarılmış halini temizleyerek boş bir şablon elde etmiş olursunuz. Sisteme Excel ile yükleme yaptığınızda yüklenen ürünlerin Ürün Kodu alanlarına göre kayıtlar indislenir. Eğer bir ürünün kodu sistemde mevcut ise ürünün bilgileri güncellenir, yok ise yeni ürün olarak sisteme eklenir. Var olan bir ürünün kodu bu yöntemle değiştirilemez! Yüklenen ürünlerin kategori adları, vergi oranı tanım adı ve varsa marka adı doğru girilmelidir. Tavsiyemiz mevcut ürünlere ait kayıtları dışarı aktarıp daha sonra bu kayıtları örnek alarak işlem yapmanız. İçeri tüm ürünler aktarıldığında ürün listesine yönlendirilirsiniz, hatalı ürünler olduğunda ise hatalı girdiğiniz ürünlerin listesi yine bir Excel dosyasında otomatik indirmeye gönderilecektir. Hatalı ürünleri indirip tekrar düzelterek sisteme aktarabilirsiniz.
    </p>
</div>

@using (Html.BeginForm("ImportExcel", "CatalogManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-sm-3">Excel Dosyası</label>
            <div class="col-sm-9">
                <input type="file" name="excel" class="form-control" />
            </div>
        </div>
        @Html.Partial("EditorTemplates/Submit")
    </div>
}

SmartBazaarWeb/Areas/Admin/Views/CatalogManager/Index.cshtml
@using SmartBazaar.Web.Areas.Admin.Models
@model IEnumerable<CatalogProductListViewModel>

@{
    ViewBag.Title = "Ürünler";
    Layout = "~/Areas/Admin/Views/Shared/LayoutTemplates/ListLayout.cshtml";
    ViewBag.CreateUrl = @Url.Action("Create");
    ViewBag.FilterExtra = true;
}


@section Breadcumbs {
    <li>
        <a href="@Url.Action("Index")">Ürünler</a>
    </li>
}
@section Filters {
    <div class="form-group col-sm-2">
        <button class="btn btn-primary" type="submit" name="export" value="excel">
            <i class="fa fa-file-excel-o"></i> Aktar
        </button>
    </div>
    <div class="form-group col-sm-7">
        <label class="control-label col-sm-4">Durum:</label>
        <div class="col-sm-8">
            @Html.DropDownList("Status", null, new { @class = "form-control" })
        </div>
    </div>
}

<tr>
    <th>
        @Html.DisplayNameFor(model => model.ProductCode)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Title)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CategoryTitle)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.BrandTitle)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Stock)
    </th>
    <th style="width: 80px;">
        @Html.DisplayNameFor(model => model.Status)
    </th>
    <th style="width: 120px;"></th>
</tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrandTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }, new { @class = "label label-primary" })
            @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = "label label-danger", onclick = "return confirm('Kayit silinsin mi?')" })
        </td>
    </tr>
}

@section Subhtml {
    <div style="display: none;" class="modal fade" id="mdlFilterExtra" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                @using (Html.BeginForm("Index", "CatalogManager", FormMethod.Get))
                {
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Detaylı Arama</h4>
                    </div>
                    <div class="modal-body">

                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="control-label col-sm-3">Durum</label>
                                <div class="col-sm-9">
                                    @Html.DropDownList("Status", null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">Ürün Kodu</label>
                                <div class="col-sm-9">
                                    @Html.TextBox("ProductCode", null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">Ürün Adı</label>
                                <div class="col-sm-9">
                                    @Html.TextBox("Caption", null, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">Kategori</label>
                                <div class="col-sm-9">
                                    @Html.DropDownList("Category", null, "Tümü",  new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">Marka</label>
                                <div class="col-sm-9">
                                    @Html.DropDownList("Brand", null, "Tümü", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">Stok</label>
                                <div class="col-sm-9">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            @Html.TextBox("StockMin", null, new { @class = "form-control", placeholder = "Min" })
                                        </div>
                                        <div class="col-sm-6">
                                            @Html.TextBox("StockMax", null, new { @class = "form-control", placeholder = "Max" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-filter"></i> Filtrele
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
}